### PR TITLE
addded julia implementations

### PR DESCRIPTION
**Pull request by lmiq**
Dear @paugier ,

I have added some different implementations in Julia. This pull request is not meant to be real, I just didn't know how to let you know about them otherwise. Accept it or close as you wish.

What I would be grateful is if you are able to confirm these benchmarks in comparison with your other implementations.

All the best,
Leandro.

### CODE REVIEW

**Comment by darleybarreto** [comment]
Thank you so much @lmiq for putting time into this. The resulting implementation looks really nice, I've been learning so much from it.  I've noticed that `show = false`, I think all the other benchmarks have the equivalente option as `true`, varying the frequency of print, perhaps making them log in the same frequency (`step % 100`) would be great. What do you think, @paugier?

**Comment by lmiq** [comment]
With the printing frequency that is set I didn't measure any significant difference. (Removed the printing to have a cleaner output). It would be nice to compare the time in the same machine as the other ones. (I am using Julia 1.5.3 by the way).

**Comment by paugier** [comment]
Great! Thank you for this contribution!

Can you please add a bit of information of the requirements and how to install them? Unfortunately, with Julia from Ubuntu 20.04 (Julia 1.4.1), I get first an error with StaticArrays and then, after installation, a syntax error.

```
time julia -O3 --check-bounds=no -- run.jl nbabel3.jl ../data/input1k false
44.84user 0.34system 0:44.75elapsed 100%CPU (0avgtext+0avgdata 293696maxresident)k
0inputs+0outputs (0major+74059minor)pagefaults 0swaps
ERROR: LoadError: LoadError: syntax: invalid named tuple element "Ekin"
Stacktrace:
 [1] top-level scope at /home/pierre/Dev/nbabel/julia/nbabel3.jl:34
 [2] include(::String) at ./client.jl:439
 [3] top-level scope at /home/pierre/Dev/nbabel/julia/run.jl:1
 [4] include(::Module, ::String) at ./Base.jl:377
 [5] exec_options(::Base.JLOptions) at ./client.jl:288
 [6] _start() at ./client.jl:484
in expression starting at /home/pierre/Dev/nbabel/julia/nbabel3.jl:34
in expression starting at /home/pierre/Dev/nbabel/julia/run.jl:1
Command exited with non-zero status 1
6.12user 0.67system 0:05.89elapsed 115%CPU (0avgtext+0avgdata 490456maxresident)k
632inputs+2096outputs (3major+186985minor)pagefaults 0swaps
```

**Comment by lmiq** [comment]
In principle you only need to start Julia and run:

`] add StaticArrays`

But I tested it on Julia 1.5.3, so if you prefer to wait I will test it with that other version and write some instructions.

**Comment by paugier** [comment]
I installed Julia 1.5.3 and managed to run the benchmarks. However, the instructions are not really for me today. It would be good anyway to have explicit requirements.

About the benchmark, the last version (nbabel4.jl) is slightly faster than the Python version (7% on input1k) so it is very good to have it. However, there is something that may be improved (?). I don't like the `--check-bounds=no` for the whole program and without this option, it becomes 1.5 times slower. IMHO, it would be better to avoid it for the whole program and to activate it only for the most important function for speed (`compute_acceleration`). Would it be possible? My point is that we can be quite sure that we don't need bound checks for one particular function but for the rest of the program that can be modified / extended (in a real life situation), I don't like to have to run things with `--check-bounds=no`. Do you see what I mean?

Lastly, it would be nice to have a pure sequential fast version. The other implementations didn't play with parallelization so to compare the complexity/readability/maintainability of the code, this Julia implementation would be somehow disadvantaged just because it does more than the others.

Do what you want with these remarks and then I merge! Thanks again.

**Comment by lmiq** [comment]
The previous commit now has two versions, one to run only in serial, the only to run possibly in parallel. The bound checking is particularly important for the parallel version, probably because of the large arrays that are being used in this implementation to avoid concurrency (I have not implemented something particularly fancy for this parallel version).

(also, probably this is a matter of taste, I usually do not use inbound flags anywhere, I prefer to use the flag when running actual production runs - at the end this is what we do when running codes written in low-level languages anyway).

I have included the benchmarks of the serial and parallel version. None of them need anymore the `StaticArrays` and they should run fine in Julia 1.4. (actually the reason for running before was a small syntax flexibility that was allowed only in 1.5).

I also made some minor changes in the code to make it a little bit more "Julian".

I hope you find this interesting. It was a nice training for me.

**Pull request merged**
