### PR TITLE
Improved Julia version

### PR DESCRIPTION
**Pull request by Arkoniak**
This is continuation of https://discourse.julialang.org/t/nbabel-nbody-integrator-speed-up/51712/53

This version shows better results on my laptop, compared to nbabel4.

Can you run it locally please and compare with `python` version? It's really interesting to know how it performs compared to transonic version.

### CODE REVIEW

**Comment by paugier** [comment]
Yes, this version is clearly a bit faster! 25-30% faster than the Python version using Pythran. Moreover, it is simpler that the version with the `struct`!

**Comment by paugier** [comment]
See https://github.com/paugier/nbabel/commit/d8a32318941b3a2293e16b889512a2ab4f888da8 for the exact results on my PC.

**Comment by Arkoniak** [comment]
Well, I hope that maybe you'll be interested enough to start next project in Julia :-) It definitely  worth it, and with PyCall.jl one can still write python frontends, so everyone can benefit.

**Comment by paugier** [comment]
Don't worry, I'm interested by Julia. I think it's really important to know what can be done in Julia but working on improving Python ecosystem is also an important task.

Having a simple implementation in Python that is only 30% slower than a fast Julia implementation is already very good. For me, a 30% difference in perf is not a big issue. This just means that we can still improve things with Python!

**Pull request merged**
