### PR TITLE
optimise code

### PR DESCRIPTION
**Pull request by bolverk**

### CODE REVIEW

**Comment by paugier** [comment]
Thanks a lot! On my PC, this (sequential) C++ implementation is a bit faster than the (sequential) Python implementation using Pythran. It's a bit slower than the optimized Julia implementation.

I'm going to mention that in the README. Other optimizations are of course welcome.

**Comment by paugier** [comment]
See 0555e69b2c6b92051ea28fa1fb1f9d61f3f32798 for the exact figures obtained with my PC.

Besides, it is of course important to keep the suboptimal implementation got from nbabel.org !

**Comment by isuruf** [comment]
> Besides, it is of course important to keep the suboptimal implementation got from nbabel.org !

Why is it important? The suboptimal implementation from nbabel.org does twice the work as any other implementation.

**Comment by ashwinvis** [comment]
> Why is it important? The suboptimal implementation from nbabel.org does twice the work as any other implementation.

@isuruf Because that code's performance was included in the published article (see Citation in the README) and should be kept as is for archival reasons. We do make it clear that the  C++ and Fortran implementations were taken as is from nbabel.org. We also mention in the article: "Note that these implementations could have been further optimized, but are representative of code written by many scientists."

I do have a question: is this loop criterion correct. Wouldn't it short circuit halfway if `sj == si`?

https://github.com/paugier/nbabel/blob/0555e69b2c6b92051ea28fa1fb1f9d61f3f32798/cpp/main_opt.cpp#L83

**Comment by paugier** [comment]
@isuruf  One of our points of our note in Nature Astro is that the implementation is more important than the language. This C++ implementation found in nbabel.org has been written by someone knowing C++ and has been used by Zwart (2020). Many real word C++ programs also miss simple algorithmic optimizations.

The goal of our work is not to check how much C++ can be push. Of course, one can write in C++ a very efficient implementation of this problem. It's evident!

We studied a question about Python. "Do we have to avoid this language for ecological reasons?"

**Comment by ashwinvis** [comment]
I don't understand and it does not make sense even if I [check the equations](http://nbabel.org/equations). The summations should be over **all other particles** and **not all particles before its position** in the vector.

**Comment by isuruf** [comment]
It's the same reason as the python implementation does the summation over all particle after its position as in https://github.com/paugier/nbabel/blob/master/py/bench.py#L43.

The reason is `i, j`  and `j, i` are updated at the same time as in https://github.com/paugier/nbabel/blob/master/cpp/main_opt.cpp#L94-L95 and https://github.com/paugier/nbabel/blob/master/py/bench.py#L43.

**Comment by ashwinvis** [comment]
See this test case:

```cpp
#include <vector>
#include <iostream>

int main() {
    std::vector<int> v = { 1, 2, 3, 4, 5 };  //intialize vector using an initializer_list

    for (std::vector<int>::iterator it = v.begin(); it != v.end(); ++it) {
			for (std::vector<int>::iterator iu = v.begin(); it != iu; ++iu) {
        std::cout << *iu << ", " << *it << std::endl;
			}
		}

    return 0;
}
```

and its output

```
1, 2
1, 3
2, 3
1, 4
2, 4
3, 4
1, 5
2, 5
3, 5
4, 5
```

**Comment by ashwinvis** [comment]
> The reason is i, j and j, i are updated at the same time 

OK I get it now. Thanks :)

**Pull request merged**
